### ISSUE TITLE
quicktools error in Blender 2.69

### ISSUE THREAD

**Issue by riveter1** [CGCookie/script-bakery#128]
I get an error when I activate the quicktools addon in Blender 2.69.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.69\scripts\modules\addon_utils.py", line 298, in enable
    mod = **import**(module_name)
  File "C:\Users\Mark\AppData\Roaming\Blender Foundation\Blender\2.69\scripts\addons\quicktools__init__.py", line 28, in <module>
    from . import quick_operators, quick_object_mode, quick_edit_mode, quick_sculpt_mode, quick_mode_switch, quick_scene
ImportError: cannot import name quick_operators

**Comment by VESPERDESIGN** [comment]
Hey i have the exact same issue. in 2.68 absolutely no problem and for a while 2.69 worked but now it creates problems.  but i found a solution :)

FIRST
1. I uninstalled the scripts and re installed and no luck.
2. I uninstalled the user prefs and loaded factory settings- no luck
3.eliminated newer scripts to avoid script conflict no luck!
4. cleared the computer cache and app data cache no luck

When i did all this i finally decided to check through previous versions of blender i had perhaps installed. I remembered i had another copy of 2.69 which was a build that caused problems. I also looked for all the physics cache folders like fluid and fabric, soft body that i no longer used. I deleted the old copy of blender 2.69>installed the factory settings with the build on the blender website>loaded quicktools from system prefs and voila!!!!!!!!

So my advice get rid of any other blender 2.69 you might have and secondly delete all cached folders that are not in use! Also don't forget to delete the cache file in :

C:\Users\Mark\AppData\Roaming\Blender Foundation\Blender\2.69\scripts\addons\

Have a good day! :)

**Comment by carter2422** [comment]
@VESPERDESIGN it sounds to me like the issue was due to your _ pycache _ directory (without spaces). This can be found in /scripts/addons/. Simply deleting the folder will cause Blender to rewrite the cache, doing basically the same thing as reinstalling Blender. 

Or at least I believe that should do the trick.

**Comment by VESPERDESIGN** [comment]
your absolutely right man it was the final part that you mentioned that did it! great work by the way on the tool i can't thank you enough it has so drastically facilitated my work flow. one question though am i able to implement or replace a shortcut. i wanted to replace the knife with bisect tool which i am using more frequently? Or should i expect it in the next release? Again great work and thank you for all your hard work!!!
