### ISSUE TITLE
Error with removing keymaps upon disabling add-on

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#54]
```
Error: Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Blender-Builds/blender-build/cmake/bin/blender.app/Contents/MacOS/2.67/scripts/modules/addon_utils.py", line 350, in disable
    mod.unregister()
  File "/Users/jonathanwilliamson/Dropbox/resources/repositories/cgCookie/script-bakery/scripts/addons/quicktools/__init__.py", line 136, in unregister
    quick_object_mode.unregister()
  File "/Users/jonathanwilliamson/Dropbox/resources/repositories/cgCookie/script-bakery/scripts/addons/quicktools/../quicktools/quick_object_mode.py", line 111, in unregister
    wm.keyconfigs.addon.keymaps.remove(km)
AttributeError: 'bpy_prop_collection' object has no attribute 'remove'
```

**Comment by carter2422** [comment]
Seems this is fixed since https://github.com/CGCookie/script-bakery/commit/bfc5fc3267988c53b2dd3bec1ae0bea65bd606dc
