### ISSUE TITLE
Cannot change number of segments

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#60]
Get this error:

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox/resources/repositories/cgCookie/script-bakery/scripts/addons/contour_tools/__init__.py", line 652, in modal
    if cut_line.head.world_position:
AttributeError: 'NoneType' object has no attribute 'world_position'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox/resources/repositories/cgCookie/script-bakery/scripts/addons/contour_tools/__init__.py", line 275, in retopo_draw_callback
    if len(self.cut_lines) > 0:
  File "/Users/jonathanwilliamson/Blender-Builds/blender-build/cmake/bin/blender.app/Contents/MacOS/2.67/scripts/modules/bpy_types.py", line 569, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGCOOKIE_OT_retopo_contour has been removed
```

**Comment by patmo141** [comment]
I'm having no problem with the number of segments.  I think this was a forgotten piece that got committed later.
