### ISSUE TITLE
Widget Error

### ISSUE THREAD

**Issue by carter2422** [CGCookie/script-bakery#72]
One of our testers, Philippe M. is removing major problems with the widget. It's happening to him almost the time. I've not yet been able to repo it, though. He's using Blender 2.68 64bit Linux official.

```
# Clicked-and-dragged into the rotate symbol in the contour-stroke widget, got this error:

Traceback (most recent call last):
  File "/home/meshweaver/.config/blender/2.68/scripts/addons/contour_tools/__init__.py", line 583, in modal
    self.drag_target.cut_object(context, self.original_form, self.bme)
  File "/home/meshweaver/.config/blender/2.68/scripts/addons/contour_tools/../contour_tools/contour_classes.py", line 402, in cut_object
    cross = contour_utilities.cross_section_seed(bme, mx, pt, pno, indx, debug = True)   
  File "/home/meshweaver/.config/blender/2.68/scripts/addons/contour_tools/../contour_tools/contour_utilities.py", line 1300, in cross_section_seed
    seeds.append([face for face in ed.link_faces if face.index != seed_index][0])
IndexError: list index out of range

location: <unknown location>:-1
```

He also did a video to show the problem: https://www.dropbox.com/s/nqn3z3b28rqbi4j/ContourRetopo_StrokeError.avi

**Comment by patmo141** [comment]
Have him email/dropbox me a .blend. it sounds like an underlying mesh problem. Ill he home around 8pm tonight hopefully I can nip a few of these in the bud by tomorrow.

**Comment by carter2422** [comment]
@patmo141 that was my guess as well.

Here is the .blend: https://www.dropbox.com/s/896dz28w2fgc7fx/PhilippeM_ContourRetopoTest.blend.7z

**Comment by patmo141** [comment]
Yeah, the mesh has lots of non manifold edges and doubles.  These represent discontinuities in the mesh.  Mesh should be a single surface or water tight.  a remove doubles seems to weld everything together nicely and I get normal behavior.

Non manifold edges
![non manifold failure](https://f.cloud.github.com/assets/2917743/883191/d0394076-f97a-11e2-851c-8424311ede23.png)

Simple weld with remove doubles
![after_doubles_removal](https://f.cloud.github.com/assets/2917743/883192/dc339aca-f97a-11e2-9812-7b94acfe74eb.png)

Succesful Retopo Afterward
![succesful_retopo](https://f.cloud.github.com/assets/2917743/883200/e354a862-f97a-11e2-8eec-3a23f4708cd8.png)

**Comment by carter2422** [comment]
Rather than crashing, can we have it toss an error to the INFO bar when bad meshes are detected?
